operator:
  sloChecker:
    droppedRecordsKStreams:
      enabled: false
  resultsVolume:
    enabled: false

strimzi:
  kafka:
    replicas: 1
    config: 
      "offsets.topic.replication.factor": "1"
  zookeeper:
    replicas: 1
  