title: "Theodolite"
description: >-
  Theodolite is a framework for benchmarking the horizontal and vertical
  scalability of cloud-native applications.

remote_theme: pmarsceill/just-the-docs
aux_links:
    "Theodolite on GitHub":
      - "//github.com/cau-se/theodolite"

exclude:
  - "*.tmpl"
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - drafts/
